---
services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  _instanceof:
    Api\Console\Action:
      tags:
        - 'console.command'

  Api\Console\:
    resource: '../../src/Api/Console'

  Api\Console\Action\CreateBranch:
    configurator: '@Api\Console\Action\CreateBranch\Configurator'

  Api\Console\Input\BranchName:
    tags:
      - { name: 'api.console.createbranch.input', priority: 100 }

  Api\Console\Input\Uri:
    tags:
      - { name: 'api.console.createbranch.input', priority: 2 }
