---
services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


  Ergebnis\Json\Normalizer\Normalizer: '@Ergebnis\Json\Normalizer\ChainNormalizer'
  Ergebnis\Json\Normalizer\ChainNormalizer:
    arguments:
      - '@Ergebnis\Json\Normalizer\IndentNormalizer'
  Ergebnis\Json\Normalizer\IndentNormalizer:
    arguments:
      - '@Ergebnis\Json\Normalizer\Format\Indent'
      - '@Ergebnis\Json\Printer\PrinterInterface'

  Ergebnis\Json\Normalizer\Format\Indent:
    factory: [null, 'fromSizeAndStyle']
    arguments:
      - 2
      - 'space'

  Ergebnis\Json\Printer\PrinterInterface: '@Ergebnis\Json\Printer\Printer'
  Ergebnis\Json\Printer\Printer: ~
