---
# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/App'

  Infra\:
    resource: '../src/Infra'
    exclude:
      - '../src/Infra/DependencyInjection/'
      - '../src/Infra/Entity/'
      - '../src/Infra/Kernel.php'

  RpHaven\Games\:
    resource: '../src/Games'


  _instanceof:
    App\Query\QueryHandler:
      tags:
        - { name: messenger.message_handler, bus: 'query.bus' }
    App\Command\CommandHandler:
      tags:
        - { name: messenger.message_handler, bus: 'command.bus' }

    Infra\Repository\Dbal\Persists:
      bind:
        $connection: '@doctrine.dbal.command_connection'
    Infra\Repository:
      tags:
        - 'infra.repository'




