---
# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

imports:
  - { resource: services/ }

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/App'
  Infra\:
    resource: '../src/Infra'
    exclude:
      - '../src/Infra/DependencyInjection/'
      - '../src/Infra/Entity/'
      - '../src/Infra/Kernel.php'
  RpHaven\Games\:
    resource: '../src/Games'



  _instanceof:
    Api\Http\Action:
      tags:
        - 'controller.service_arguments'
    Infra\Repository\Dbal\Persists:
      bind:
        $connection: '@doctrine.dbal.command_connection'
    Infra\Repository:
      tags:
        - 'infra.repository'
    App\Query\QueryHandler:
      tags:
        - { name: messenger.message_handler, bus: 'query.bus' }
    App\Command\CommandHandler:
      tags:
        - { name: messenger.message_handler, bus: 'command.bus' }


  Api\Http\EventListener\:
    resource: '../src/Api/Http/EventListener'
    tags: [ 'kernel.event_listener' ]

  Symfony\Bridge\PsrHttpMessage\HttpFoundationFactoryInterface: '@Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory'
  Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory: ~
  Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface: '@Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory'
  Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory: ~
  Symfony\Bridge\PsrHttpMessage\ArgumentValueResolver\PsrServerRequestResolver:
    tags: ['controller.argument_value_resolver']


